### ISSUE TITLE
A/B Test images not showing

### ISSUE THREAD

**Issue by mababaj** [episerver/AlloyDemoKit#14]
Maybe since the image resizer got changed? I can't see how though... or it could be the new submitted form KPI?

**Comment by davidknipe** [comment]
Reinstalling the EPiServer.Marketing.Testing fixes the issue. Its caused due to a missing .exe here: https://github.com/episerver/AlloyDemoKit/tree/master/src/AlloyDemoKit/modules/_protected/EPiServer.Marketing.Testing/abcapture. The missing .exe needs to be added to source control and committed. cc: @vnbaaij

**Comment by mababaj** [comment]
Thank you! Worked perfectly

**Comment by mababaj** [comment]
sorry - leaving open for exe to be put in the source control @vnbaaij

**Comment by vnbaaij** [comment]
The exe is now included

**Comment by mababaj** [comment]
thank you 🥇
